### ISSUE TITLE
fe code setup issue

### ISSUE THREAD

**Issue by chenxuanrong** [InfuseAI/piperider#392]
**Describe the bug**

Local setup and start single report failed.

**To Reproduce**
1. Setup environment:  
```
node --version              
v14.18.1
```
2. Execute command
```
yarn
yarn run start:single
```
3. See error
```
index.js:19 Uncaught RangeError: Invalid time value
    at DateTimeFormat.formatToParts (<anonymous>)
    at partsTimeZone (index.js:19:1)
    at tzIntlTimeZoneName (index.js:15:1)
    at Object.z (index.js:100:1)
    at index.js:344:1
    at Array.reduce (<anonymous>)
    at format (index.js:337:1)
    at formatInTimeZone (index.js:41:1)
    at formatReportTime (formatters.tsx:20:1)
    at SRTablesListPage (SRTablesListPage.tsx:27:1)
react-dom.development.js:18687 The above error occurred in the <SRTablesListPage> component:

    at SRTablesListPage (http://localhost:3002/static/js/bundle.js:3435:5)
    at component
    at Route (http://localhost:3002/static/js/bundle.js:356378:5)
    at Switch (http://localhost:3002/static/js/bundle.js:356432:5)
    at Router (http://localhost:3002/static/js/bundle.js:356364:69)
    at Suspense
    at AppSingle
    at App
    at EnvironmentProvider (http://localhost:3002/static/js/bundle.js:26937:24)
    at ColorModeProvider (http://localhost:3002/static/js/bundle.js:15589:21)
    at ThemeProvider (http://localhost:3002/static/js/bundle.js:44696:64)
    at ThemeProvider (http://localhost:3002/static/js/bundle.js:32475:27)
    at ChakraProvider (http://localhost:3002/static/js/bundle.js:26228:24)
    at ChakraProvider (http://localhost:3002/static/js/bundle.js:27649:23)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:26923 Uncaught RangeError: Invalid time value
    at DateTimeFormat.formatToParts (<anonymous>)
    at partsTimeZone (index.js:19:1)
    at tzIntlTimeZoneName (index.js:15:1)
    at Object.z (index.js:100:1)
    at index.js:344:1
    at Array.reduce (<anonymous>)
    at format (index.js:337:1)
    at formatInTimeZone (index.js:41:1)
    at formatReportTime (formatters.tsx:20:1)
    at SRTablesListPage (SRTablesListPage.tsx:27:1)

```

While in terminal everything looks successful.
```
Compiled successfully!

You can now view piperider-report in the browser.

  Local:            http://localhost:3002
  On Your Network:  http://192.168.1.159:3002

Note that the development build is not optimized.
To create a production build, use yarn build.

webpack compiled successfully
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.

```

**Expected behavior**

Setup run successfully and can serve report locally

**Screenshots**

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/90671468/187147610-315c31b5-3935-4849-8e53-8babca571fd6.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version 3.7.10
 - Piperider Version 0.8.0-dev

**Additional context**

I've followed README.md in static reports folder to init,  generated single and comparison report with some sample datasets.

**Comment by DaveFlynn** [comment]
Hi chenxuanrong,

Based on the provided information, the issue appears to be in the generated run.json file, specifically the format of a datetime.

Would you be able to provide us with either your run.json file or, if this contains sensitive information, an anonymized sample of your source data so we can try to recreate the issue?

Also, if you use the same data source in the latest stable release, do you have the same issue?

Thanks,

Dave

**Comment by chenxuanrong** [comment]
Hi @DaveFlynn 

Please see the sample data I used.

<details>

<summary>single-report run.json</summary>

```json
{
    "tables": {
        "apmdb_eventtype": {
            "name": "apmdb_eventtype",
            "row_count": 38,
            "col_count": 8,
            "columns": {
                "eventtypeid": {
                    "name": "eventtypeid",
                    "type": "numeric",
                    "schema_type": "DECIMAL(38, 0)",
                    "total": 38,
                    "non_nulls": 38,
                    "nulls": 0,
                    "valids": 38,
                    "invalids": 0,
                    "zeros": 0,
                    "negatives": 0,
                    "positives": 38,
                    "distinct": 38,
                    "min": 1,
                    "max": 38,
                    "sum": 741,
                    "avg": 19.5,
                    "stddev": 10.965856099730654,
                    "duplicates": 0,
                    "non_duplicates": 38,
                    "histogram": {
                        "labels": [
                            "1.00 _ 1.74",
                            "1.74 _ 2.48",
                            "2.48 _ 3.22",
                            "3.22 _ 3.96",
                            "3.96 _ 4.70",
                            "4.70 _ 5.44",
                            "5.44 _ 6.18",
                            "6.18 _ 6.92",
                            "6.92 _ 7.66",
                            "7.66 _ 8.40",
                            "8.40 _ 9.14",
                            "9.14 _ 9.88",
                            "9.88 _ 10.62",
                            "10.62 _ 11.36",
                            "11.36 _ 12.10",
                            "12.10 _ 12.84",
                            "12.84 _ 13.58",
                            "13.58 _ 14.32",
                            "14.32 _ 15.06",
                            "15.06 _ 15.80",
                            "15.80 _ 16.54",
                            "16.54 _ 17.28",
                            "17.28 _ 18.02",
                            "18.02 _ 18.76",
                            "18.76 _ 19.50",
                            "19.50 _ 20.24",
                            "20.24 _ 20.98",
                            "20.98 _ 21.72",
                            "21.72 _ 22.46",
                            "22.46 _ 23.20",
                            "23.20 _ 23.94",
                            "23.94 _ 24.68",
                            "24.68 _ 25.42",
                            "25.42 _ 26.16",
                            "26.16 _ 26.90",
                            "26.90 _ 27.64",
                            "27.64 _ 28.38",
                            "28.38 _ 29.12",
                            "29.12 _ 29.86",
                            "29.86 _ 30.60",
                            "30.60 _ 31.34",
                            "31.34 _ 32.08",
                            "32.08 _ 32.82",
                            "32.82 _ 33.56",
                            "33.56 _ 34.30",
                            "34.30 _ 35.04",
                            "35.04 _ 35.78",
                            "35.78 _ 36.52",
                            "36.52 _ 37.26",
                            "37.26 _ 38.00"
                        ],
                        "counts": [
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1
                        ],
                        "bin_edges": [
                            1.0,
                            1.74,
                            2.48,
                            3.22,
                            3.96,
                            4.7,
                            5.44,
                            6.18,
                            6.92,
                            7.66,
                            8.4,
                            9.14,
                            9.88,
                            10.620000000000001,
                            11.36,
                            12.1,
                            12.84,
                            13.58,
                            14.32,
                            15.06,
                            15.8,
                            16.54,
                            17.28,
                            18.02,
                            18.76,
                            19.5,
                            20.240000000000002,
                            20.98,
                            21.72,
                            22.46,
                            23.2,
                            23.94,
                            24.68,
                            25.42,
                            26.16,
                            26.900000000000002,
                            27.64,
                            28.38,
                            29.12,
                            29.86,
                            30.6,
                            31.34,
                            32.08,
                            32.82,
                            33.56,
                            34.300000000000004,
                            35.04,
                            35.78,
                            36.52,
                            37.26,
                            38.0
                        ]
                    },
                    "p5": 2,
                    "p25": 10,
                    "p50": 19,
                    "p75": 29,
                    "p95": 37,
                    "distribution": {
                        "type": "histogram",
                        "labels": [
                            "1.00 _ 1.74",
                            "1.74 _ 2.48",
                            "2.48 _ 3.22",
                            "3.22 _ 3.96",
                            "3.96 _ 4.70",
                            "4.70 _ 5.44",
                            "5.44 _ 6.18",
                            "6.18 _ 6.92",
                            "6.92 _ 7.66",
                            "7.66 _ 8.40",
                            "8.40 _ 9.14",
                            "9.14 _ 9.88",
                            "9.88 _ 10.62",
                            "10.62 _ 11.36",
                            "11.36 _ 12.10",
                            "12.10 _ 12.84",
                            "12.84 _ 13.58",
                            "13.58 _ 14.32",
                            "14.32 _ 15.06",
                            "15.06 _ 15.80",
                            "15.80 _ 16.54",
                            "16.54 _ 17.28",
                            "17.28 _ 18.02",
                            "18.02 _ 18.76",
                            "18.76 _ 19.50",
                            "19.50 _ 20.24",
                            "20.24 _ 20.98",
                            "20.98 _ 21.72",
                            "21.72 _ 22.46",
                            "22.46 _ 23.20",
                            "23.20 _ 23.94",
                            "23.94 _ 24.68",
                            "24.68 _ 25.42",
                            "25.42 _ 26.16",
                            "26.16 _ 26.90",
                            "26.90 _ 27.64",
                            "27.64 _ 28.38",
                            "28.38 _ 29.12",
                            "29.12 _ 29.86",
                            "29.86 _ 30.60",
                            "30.60 _ 31.34",
                            "31.34 _ 32.08",
                            "32.08 _ 32.82",
                            "32.82 _ 33.56",
                            "33.56 _ 34.30",
                            "34.30 _ 35.04",
                            "35.04 _ 35.78",
                            "35.78 _ 36.52",
                            "36.52 _ 37.26",
                            "37.26 _ 38.00"
                        ],
                        "counts": [
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1,
                            0,
                            1,
                            1,
                            1
                        ],
                        "bin_edges": [
                            1.0,
                            1.74,
                            2.48,
                            3.22,
                            3.96,
                            4.7,
                            5.44,
                            6.18,
                            6.92,
                            7.66,
                            8.4,
                            9.14,
                            9.88,
                            10.620000000000001,
                            11.36,
                            12.1,
                            12.84,
                            13.58,
                            14.32,
                            15.06,
                            15.8,
                            16.54,
                            17.28,
                            18.02,
                            18.76,
                            19.5,
                            20.240000000000002,
                            20.98,
                            21.72,
                            22.46,
                            23.2,
                            23.94,
                            24.68,
                            25.42,
                            26.16,
                            26.900000000000002,
                            27.64,
                            28.38,
                            29.12,
                            29.86,
                            30.6,
                            31.34,
                            32.08,
                            32.82,
                            33.56,
                            34.300000000000004,
                            35.04,
                            35.78,
                            36.52,
                            37.26,
                            38.0
                        ]
                    },
                    "profile_duration": "1.08",
                    "elapsed_milli": 1077,
                    "description": "Description: N/A"
                },
                "eventtypecode": {
                    "name": "eventtypecode",
                    "type": "string",
                    "schema_type": "VARCHAR(6)",
                    "total": 38,
                    "non_nulls": 38,
                    "nulls": 0,
                    "valids": 38,
                    "invalids": 0,
                    "zero_length": 0,
                    "non_zero_length": 38,
                    "distinct": 38,
                    "min": 4,
                    "max": 4,
                    "sum": 152,
                    "avg": 4.0,
                    "stddev": 0.0,
                    "duplicates": 0,
                    "non_duplicates": 38,
                    "topk": {
                        "values": [
                            "AUPP",
                            "AUFS",
                            "AUPI",
                            "AUSS",
                            "AUSN",
                            "AUTR",
                            "AUVB",
                            "PTNO",
                            "DUSR",
                            "PTSD",
                            "TNNS",
                            "PTSW",
                            "PTNA",
                            "AUPN",
                            "AUHB",
                            "ARSD",
                            "TNFS",
                            "AUSP",
                            "AUNO",
                            "AUNA"
                        ],
                        "counts": [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "histogram": {
                        "labels": [
                            "4"
                        ],
                        "counts": [
                            38
                        ],
                        "bin_edges": [
                            4,
                            5
                        ]
                    },
                    "distribution": {
                        "type": "topk",
                        "labels": [
                            "AUPP",
                            "AUFS",
                            "AUPI",
                            "AUSS",
                            "AUSN",
                            "AUTR",
                            "AUVB",
                            "PTNO",
                            "DUSR",
                            "PTSD",
                            "TNNS",
                            "PTSW",
                            "PTNA",
                            "AUPN",
                            "AUHB",
                            "ARSD",
                            "TNFS",
                            "AUSP",
                            "AUNO",
                            "AUNA"
                        ],
                        "counts": [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "profile_duration": "0.52",
                    "elapsed_milli": 515,
                    "description": "Description: N/A"
                },
                "eventtypelabel": {
                    "name": "eventtypelabel",
                    "type": "string",
                    "schema_type": "VARCHAR(50)",
                    "total": 38,
                    "non_nulls": 38,
                    "nulls": 0,
                    "valids": 38,
                    "invalids": 0,
                    "zero_length": 0,
                    "non_zero_length": 38,
                    "distinct": 38,
                    "min": 13,
                    "max": 33,
                    "sum": 832,
                    "avg": 21.894737,
                    "stddev": 5.870485240931023,
                    "duplicates": 0,
                    "non_duplicates": 38,
                    "topk": {
                        "values": [
                            "Auction - Sold After",
                            "Auction - For Sale",
                            "Auction - Sold prior (price N/A)",
                            "Auction - Sold after N/A",
                            "Auction - Sold",
                            "Auction Transferred",
                            "Conditional Sale",
                            "Private Treaty - love & affection",
                            "Dummy Seeded Result",
                            "Private Treaty not available",
                            "Tender - Sold (price N/A)",
                            "Private Treaty withdrawn",
                            "Private Treaty - For Sale",
                            "Auction - Postponed",
                            "Auction - Highest Bid",
                            "Agent reported sold",
                            "Tender - Not Sold",
                            "Auction - Sold (price N/A)",
                            "Auction - No Bid",
                            "Auction - N/A"
                        ],
                        "counts": [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "histogram": {
                        "labels": [
                            "13",
                            "14",
                            "15",
                            "16",
                            "17",
                            "18",
                            "19",
                            "20",
                            "21",
                            "22",
                            "23",
                            "24",
                            "25",
                            "26",
                            "27",
                            "28",
                            "29",
                            "30",
                            "31",
                            "32",
                            "33"
                        ],
                        "counts": [
                            3,
                            1,
                            0,
                            4,
                            2,
                            1,
                            6,
                            3,
                            2,
                            0,
                            1,
                            2,
                            2,
                            1,
                            1,
                            2,
                            2,
                            1,
                            1,
                            1,
                            2
                        ],
                        "bin_edges": [
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                            27,
                            28,
                            29,
                            30,
                            31,
                            32,
                            33,
                            34
                        ]
                    },
                    "distribution": {
                        "type": "topk",
                        "labels": [
                            "Auction - Sold After",
                            "Auction - For Sale",
                            "Auction - Sold prior (price N/A)",
                            "Auction - Sold after N/A",
                            "Auction - Sold",
                            "Auction Transferred",
                            "Conditional Sale",
                            "Private Treaty - love & affection",
                            "Dummy Seeded Result",
                            "Private Treaty not available",
                            "Tender - Sold (price N/A)",
                            "Private Treaty withdrawn",
                            "Private Treaty - For Sale",
                            "Auction - Postponed",
                            "Auction - Highest Bid",
                            "Agent reported sold",
                            "Tender - Not Sold",
                            "Auction - Sold (price N/A)",
                            "Auction - No Bid",
                            "Auction - N/A"
                        ],
                        "counts": [
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1,
                            1
                        ]
                    },
                    "profile_duration": "0.61",
                    "elapsed_milli": 605,
                    "description": "Description: N/A"
                },
                "activitytypeid": {
                    "name": "activitytypeid",
                    "type": "numeric",
                    "schema_type": "DECIMAL(38, 0)",
                    "total": 38,
                    "non_nulls": 38,
                    "nulls": 0,
                    "valids": 38,
                    "invalids": 0,
                    "zeros": 0,
                    "negatives": 0,
                    "positives": 38,
                    "distinct": 2,
                    "min": 1,
                    "max": 2,
                    "sum": 42,
                    "avg": 1.105263,
                    "stddev": 0.30689277364449363,
                    "duplicates": 38,
                    "non_duplicates": 0,
                    "histogram": {
                        "labels": [
                            "1.00 _ 1.02",
                            "1.02 _ 1.04",
                            "1.04 _ 1.06",
                            "1.06 _ 1.08",
                            "1.08 _ 1.10",
                            "1.10 _ 1.12",
                            "1.12 _ 1.14",
                            "1.14 _ 1.16",
                            "1.16 _ 1.18",
                            "1.18 _ 1.20",
                            "1.20 _ 1.22",
                            "1.22 _ 1.24",
                            "1.24 _ 1.26",
                            "1.26 _ 1.28",
                            "1.28 _ 1.30",
                            "1.30 _ 1.32",
                            "1.32 _ 1.34",
                            "1.34 _ 1.36",
                            "1.36 _ 1.38",
                            "1.38 _ 1.40",
                            "1.40 _ 1.42",
                            "1.42 _ 1.44",
                            "1.44 _ 1.46",
                            "1.46 _ 1.48",
                            "1.48 _ 1.50",
                            "1.50 _ 1.52",
                            "1.52 _ 1.54",
                            "1.54 _ 1.56",
                            "1.56 _ 1.58",
                            "1.58 _ 1.60",
                            "1.60 _ 1.62",
                            "1.62 _ 1.64",
                            "1.64 _ 1.66",
                            "1.66 _ 1.68",
                            "1.68 _ 1.70",
                            "1.70 _ 1.72",
                            "1.72 _ 1.74",
                            "1.74 _ 1.76",
                            "1.76 _ 1.78",
                            "1.78 _ 1.80",
                            "1.80 _ 1.82",
                            "1.82 _ 1.84",
                            "1.84 _ 1.86",
                            "1.86 _ 1.88",
                            "1.88 _ 1.90",
                            "1.90 _ 1.92",
                            "1.92 _ 1.94",
                            "1.94 _ 1.96",
                            "1.96 _ 1.98",
                            "1.98 _ 2.00"
                        ],
                        "counts": [
                            34,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            4
                        ],
                        "bin_edges": [
                            1.0,
                            1.02,
                            1.04,
                            1.06,
                            1.08,
                            1.1,
                            1.12,
                            1.1400000000000001,
                            1.16,
                            1.18,
                            1.2,
                            1.22,
                            1.24,
                            1.26,
                            1.28,
                            1.3,
                            1.32,
                            1.34,
                            1.3599999999999999,
                            1.38,
                            1.4,
                            1.42,
                            1.44,
                            1.46,
                            1.48,
                            1.5,
                            1.52,
                            1.54,
                            1.56,
                            1.58,
                            1.6,
                            1.62,
                            1.6400000000000001,
                            1.6600000000000001,
                            1.6800000000000002,
                            1.7,
                            1.72,
                            1.74,
                            1.76,
                            1.78,
                            1.8,
                            1.8199999999999998,
                            1.8399999999999999,
                            1.8599999999999999,
                            1.88,
                            1.9,
                            1.92,
                            1.94,
                            1.96,
                            1.98,
                            2.0
                        ]
                    },
                    "p5": 1,
                    "p25": 1,
                    "p50": 1,
                    "p75": 1,
                    "p95": 2,
                    "distribution": {
                        "type": "histogram",
                        "labels": [
                            "1.00 _ 1.02",
                            "1.02 _ 1.04",
                            "1.04 _ 1.06",
                            "1.06 _ 1.08",
                            "1.08 _ 1.10",
                            "1.10 _ 1.12",
                            "1.12 _ 1.14",
                            "1.14 _ 1.16",
                            "1.16 _ 1.18",
                            "1.18 _ 1.20",
                            "1.20 _ 1.22",
                            "1.22 _ 1.24",
                            "1.24 _ 1.26",
                            "1.26 _ 1.28",
                            "1.28 _ 1.30",
                            "1.30 _ 1.32",
                            "1.32 _ 1.34",
                            "1.34 _ 1.36",
                            "1.36 _ 1.38",
                            "1.38 _ 1.40",
                            "1.40 _ 1.42",
                            "1.42 _ 1.44",
                            "1.44 _ 1.46",
                            "1.46 _ 1.48",
                            "1.48 _ 1.50",
                            "1.50 _ 1.52",
                            "1.52 _ 1.54",
                            "1.54 _ 1.56",
                            "1.56 _ 1.58",
                            "1.58 _ 1.60",
                            "1.60 _ 1.62",
                            "1.62 _ 1.64",
                            "1.64 _ 1.66",
                            "1.66 _ 1.68",
                            "1.68 _ 1.70",
                            "1.70 _ 1.72",
                            "1.72 _ 1.74",
                            "1.74 _ 1.76",
                            "1.76 _ 1.78",
                            "1.78 _ 1.80",
                            "1.80 _ 1.82",
                            "1.82 _ 1.84",
                            "1.84 _ 1.86",
                            "1.86 _ 1.88",
                            "1.88 _ 1.90",
                            "1.90 _ 1.92",
                            "1.92 _ 1.94",
                            "1.94 _ 1.96",
                            "1.96 _ 1.98",
                            "1.98 _ 2.00"
                        ],
                        "counts": [
                            34,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            4
                        ],
                        "bin_edges": [
                            1.0,
                            1.02,
                            1.04,
                            1.06,
                            1.08,
                            1.1,
                            1.12,
                            1.1400000000000001,
                            1.16,
                            1.18,
                            1.2,
                            1.22,
                            1.24,
                            1.26,
                            1.28,
                            1.3,
                            1.32,
                            1.34,
                            1.3599999999999999,
                            1.38,
                            1.4,
                            1.42,
                            1.44,
                            1.46,
                            1.48,
                            1.5,
                            1.52,
                            1.54,
                            1.56,
                            1.58,
                            1.6,
                            1.62,
                            1.6400000000000001,
                            1.6600000000000001,
                            1.6800000000000002,
                            1.7,
                            1.72,
                            1.74,
                            1.76,
                            1.78,
                            1.8,
                            1.8199999999999998,
                            1.8399999999999999,
                            1.8599999999999999,
                            1.88,
                            1.9,
                            1.92,
                            1.94,
                            1.96,
                            1.98,
                            2.0
                        ]
                    },
                    "profile_duration": "0.63",
                    "elapsed_milli": 630,
                    "description": "Description: N/A"
                },
                "eventchannelid": {
                    "name": "eventchannelid",
                    "type": "numeric",
                    "schema_type": "DECIMAL(38, 0)",
                    "total": 38,
                    "non_nulls": 0,
                    "nulls": 38,
                    "valids": 0,
                    "invalids": 0,
                    "zeros": 0,
                    "negatives": 0,
                    "positives": 0,
                    "distinct": 0,
                    "duplicates": 0,
                    "non_duplicates": 0,
                    "profile_duration": "0.29",
                    "elapsed_milli": 289,
                    "description": "Description: N/A"
                },
                "eventmodeid": {
                    "name": "eventmodeid",
                    "type": "numeric",
                    "schema_type": "DECIMAL(38, 0)",
                    "total": 38,
                    "non_nulls": 0,
                    "nulls": 38,
                    "valids": 0,
                    "invalids": 0,
                    "zeros": 0,
                    "negatives": 0,
                    "positives": 0,
                    "distinct": 0,
                    "duplicates": 0,
                    "non_duplicates": 0,
                    "profile_duration": "0.34",
                    "elapsed_milli": 340,
                    "description": "Description: N/A"
                },
                "etl_updated_timestamp": {
                    "name": "etl_updated_timestamp",
                    "type": "other",
                    "schema_type": "TIMESTAMP_LTZ",
                    "total": 38,
                    "non_nulls": 38,
                    "nulls": 0,
                    "valids": 38,
                    "invalids": 0,
                    "distinct": 1,
                    "profile_duration": "0.22",
                    "elapsed_milli": 216,
                    "description": "Description: N/A"
                },
                "etl_deleted_flag": {
                    "name": "etl_deleted_flag",
                    "type": "boolean",
                    "schema_type": "BOOLEAN",
                    "total": 38,
                    "non_nulls": 0,
                    "nulls": 38,
                    "valids": 0,
                    "invalids": 0,
                    "trues": 0,
                    "falses": 0,
                    "distinct": 0,
                    "distribution": {
                        "type": "topk",
                        "labels": [
                            "False",
                            "True"
                        ],
                        "counts": [
                            0,
                            0
                        ]
                    },
                    "profile_duration": "0.14",
                    "elapsed_milli": 144,
                    "description": "Description: N/A"
                }
            },
            "piperider_assertion_result": {
                "tests": [],
                "columns": {}
            },
            "description": "Description: N/A"
        }
    },
    "id": "2e6a3e4f9f7b40739defbd44596b0c21",
    "created_at": "2022-08-30T06:13:38.587743Z",
    "datasource": {
        "name": "domain",
        "type": "snowflake"
    }
}
```
</details>

`piperider generate-reports` works without issue and can render the report.
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/90671468/187803290-81c5f84e-c9b5-4f6e-a992-42290fcc8f82.png">

Thanks,
Chenxuan

**Comment by jonycfu** [comment]
Hey @chenxuanrong,
I wasn't able to reproduce the issue during serve, following your steps. 
https://www.loom.com/share/b3b6e3aee0514dbdb46dd765b4436134

Would like to investigate further, but need to be able to reproduce it on my end to better help identify the cause.

Couple things to help us along narrowing down the issue: 
* Could you perhaps check that you are on the latest of `main` branch?
* What is your browser version/info?
* What is your system OS? 
* Does this only happen for single reports? and not comparison report?

**Comment by DaveFlynn** [comment]
Hi @chenxuanrong,

We have managed to reproduce the issue.

Before running `npm run start:single`, please run compare-reports with the debug flag:

`piperider compare-reports --debug`

This creates a file `comparisons/latest/comparison_data.json`, which isn't actually required for single report, but when missing causes an error before the server is created.

Thanks for pointing us to this issue. We'll be updating the readme with the additional info soon.

Please let us know if this resolves the problem.

Dave

**Comment by chenxuanrong** [comment]
Thanks @DaveFlynn  and @jonycfu for the prompt reply.

I'm now able to set up locally.

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/90671468/187916414-f2af5610-7f6c-4ae7-8b2b-18ae66b49306.png">
